version: '3.4'
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
    - ./data:/data 
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_DB=my-app
      - POSTGRES_PORT=5432
